# Workflow name
name: Lint & Test

# Trigger setting
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  POETRY_VERSION: 1.1.10
  POETRY_URL: https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py

jobs:
  build:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/cargo@v1
        with:
          run: make test

        # - name: Build
        #   run: make build
