# Workflow name
name: Lint & Test

# Trigger setting
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Lint & Test
    runs-on: ubuntu-latest
    outputs:
      TOOL_CHAIN: nightly-2023-11-23
    env:
      RUSTC_FORCE_INCREMENTAL: 1
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/cache_cargo
    steps:
      - uses: actions-rs/cargo@v1
        with:
          run: make test

        # - name: Build
        #   run: make build
